### PR TITLE
Try travis CI

### PR DESCRIPTION
**Pull request by mfazekas**
Travis build configuration, doesn't do much yet, but builds the ios example.

Example build:
https://travis-ci.org/mfazekas/maps-1/jobs/526960739

### CODE REVIEW

**Comment by kristfal** [comment]
I like where this is going! I’ll sort out you merge permissions this week. 

Bye, we’ve been running detox quite successfully for E2E tests. I was thinking something similar would be super in this repo as well, using the example app as a test bench. Have you experience with setting up detox, and if so, how does it play with Travis?

**Comment by systemlevel** [comment]
> I like where this is going! I’ll sort out you merge permissions this week.
> 
> BTW, we’ve been running detox quite successfully for E2E tests. I was thinking something similar would be super in this repo as well, using the example app as a test bench. Have you experience with setting up detox, and if so, how does it play with Travis?

We've started using detox as well https://github.com/wix/Detox

**Comment by mfazekas** [comment]
@kristfal can you also enable the repo for travis?

https://travis-ci.org/account/repositories

also in settings we'll need to add an environment variable MAPBOX_ACCESS_TOKEN pointing to a valid env. I have an token set up for this purpose but not sure about a secure channel to send you.

**Comment by kristfal** [comment]
I got a token to use as well. Triggered a test build. I propose we ask mapbox for a free token with more tiles for CI purposes, I think they should be able to support us with one.

**Comment by nitaliano** [comment]
I got the notification for travis before and accepted it.

If we send tokens around we should use keybase to encrypt them and we can send them thru a chat or something like that and decrypt them on the other side.

I can contact Mapbox to see if they would be willing to provide us an access token.

**Pull request merged**
